import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseYaml } from '../../.codex/skills/muion-project/scripts/yaml-lite.mjs';
import { readGoalCheckpoint } from './goal-adapter.mjs';
import { buildContinuation } from './continuation-adapter.mjs';
import { evaluateConvergence } from './convergence-guard.mjs';
import { summarizeHealth } from './health-adapter.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const stateDir = path.join(ROOT,'07_research_system/control/research-state');
const read = (file, fallback) => { try { const t=fs.readFileSync(file,'utf8').replace(/^\uFEFF/,'').trim(); if(!t)return fallback; return file.endsWith('.jsonl') ? t.split(/\r?\n/).filter(Boolean).map(x=>JSON.parse(x)) : (file.endsWith('.json') ? JSON.parse(t) : parseYaml(t)); } catch(e){ throw new Error(`${path.relative(ROOT,file)}: ${e.message}`); } };
function files(dir, suffix){ try{return fs.readdirSync(dir).filter(x=>x.endsWith(suffix)).map(x=>path.join(dir,x));}catch{return [];} }
function snapshot(){ const warnings=[]; let state={}; try{state=read(path.join(stateDir,'state.yaml'),{});}catch(e){warnings.push(e.message)}
 let problems=[]; try{problems=read(path.join(stateDir,'open-problems.yaml'),[]);}catch(e){warnings.push(e.message)}
 let events=[]; try{events=read(path.join(stateDir,'events.jsonl'),[]);}catch(e){warnings.push(e.message)}
 const workflows=[]; for(const base of [path.join(stateDir,'workflows'),path.join(ROOT,'_work/current/workflows')]) for(const f of files(base,'.json')) try{workflows.push({...read(f,{}),__file:f});}catch(e){warnings.push(e.message)}
 const canonical=workflows.filter(w=>w.__file.includes(`${path.sep}07_research_system${path.sep}`)); const wf=(canonical[0]||workflows[0]||null); const stages=wf?.stages||wf?.workflow?.stages||[]; const current=wf?.current||wf?.current_stage||wf?.workflow?.current||null; const status=wf?.status||wf?.workflow?.status||null;
 const completed=[...(state.completed_stages||[]),...stages.filter(s=>['completed','done','succeeded'].includes(String(s.status).toLowerCase())).map(s=>s.id||s.name)].filter(Boolean); const pending=stages.filter(s=>!completed.includes(s.id||s.name)).map(s=>s.id||s.name); const blocked=stages.filter(s=>String(s.status).toLowerCase()==='blocked').map(s=>s.id||s.name); if(state.blocked_reason) blocked.push(state.blocked_reason); const idx=stages.findIndex(s=>(s.id||s.name)===current); const progress=wf&&stages.length ? {value:Math.max(0,idx)/stages.length,basis:'active workflow stage index'} : {value:null,basis:'no active workflow checkpoint'};
 let agents=[]; try{agents=files(path.join(ROOT,'00_project/traceability/agent-runs'),'.json').map(f=>read(f,{}));}catch(e){warnings.push(e.message)}; let farmer=null; try{farmer=read(path.join(ROOT,'_work/current/farmer/state.json'),null);}catch(e){warnings.push(e.message)}; if(farmer&&typeof farmer==='object') for(const [id,a] of Object.entries(farmer)) agents.push({source:'farmer',session_id:id,...a}); const counts={total:agents.length,running:0,done:0,failed:0}; for(const a of agents){const s=String(a.status||a.lifecycle_state||a.lifecycle||'').toLowerCase(); if(['running','turn_started'].includes(s))counts.running++; else if(['done','succeeded','success','complete'].includes(s))counts.done++; else if(['failed','error','queue_stuck','manual-attention-required'].includes(s))counts.failed++;}
 const goal=state.current_goal||wf?.goal||wf?.workflow?.goal||null; const checkpoint=readGoalCheckpoint(ROOT,wf,state); warnings.push(...checkpoint.warnings); const continuation=buildContinuation(ROOT,state,wf); warnings.push(...continuation.warnings); const convergence=evaluateConvergence({criteriaMet:state.task_status==='SUCCESS'||state.task_status==='COMPLETED',blocked:state.task_status==='BLOCKED'||blocked.length>0}); const health=summarizeHealth(agents); const times=[state.updated_at,wf?.updated_at,wf?.updatedAt,...events.map(e=>e.occurred_at)].filter(Boolean).sort(); return {generated_at:new Date().toISOString(),research_state:state,workflow:wf?{...wf,__file:undefined}:null,display:{goal,checkpoint,continuation,convergence,health,current:current||{phase:state.current_phase,task:state.current_task,question:state.current_question},completed:[...new Set(completed)],pending,blocked,next_action:wf?.next_action||state.next_action||null,open_problems:problems,progress,last_update:times.at(-1)||null},agents:{available:agents.length>0,...counts,items:agents},warnings}; }
const html=fs.readFileSync(path.join(path.dirname(fileURLToPath(import.meta.url)),'index.html'),'utf8');
export function handler(req,res){ if(req.method!=='GET'){res.writeHead(405);return res.end('Method Not Allowed');} if(req.url==='/'){res.writeHead(200,{'content-type':'text/html; charset=utf-8'});return res.end(html);} if(req.url==='/api/status'){res.writeHead(200,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});return res.end(JSON.stringify(snapshot()));} res.writeHead(404);res.end('Not Found'); }
export function start({port=Number(process.env.RESEARCH_DASHBOARD_PORT||4317),host='127.0.0.1'}={}){const s=http.createServer(handler);return new Promise(r=>s.listen(port,host,()=>{console.log(`research-dashboard listening on http://${host}:${port}`);r(s);}));}
if(process.argv[1]===fileURLToPath(import.meta.url)) start();
