import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { parseYamlFile } from '../.codex/skills/muion-project/scripts/yaml-lite.mjs';

const root = path.resolve(import.meta.dirname, '..');
const required = [
  'AGENTS.md',
  '00_project/config/delivery-policy.json',
  'README.md',
  '.gitignore',
  '.codex/skills/muion-project/SKILL.md',
  '.codex/skills/muion-project/agents/openai.yaml',
  '.codex/skills/farmer/SKILL.md',
  '.codex/skills/farmer/agents/openai.yaml',
  '.codex/skills/farmer/farmer.mjs',
  '.codex/skills/muion-project/scripts/base-content-verification.mjs',
  '.codex/skills/muion-project/scripts/ensure-toolchain.mjs',
  '.codex/skills/muion-project/scripts/audit-sync-receipt.mjs',
  '.codex/skills/muion-project/scripts/record-sync-receipt-delivery.mjs',
  '.codex/skills/muion-project/scripts/autopilot.mjs',
  '.codex/skills/team/SKILL.md',
  '.codex/skills/team/agents/openai.yaml',
  '.codex/skills/evolution/SKILL.md',
  '.codex/skills/evolution/agents/openai.yaml',
  '.codex/skills/geant4/SKILL.md',
  '.codex/skills/geant4/agents/openai.yaml',
  '.codex/skills/3d/SKILL.md',
  '.codex/skills/3d/agents/openai.yaml',
  '07_research_system/blocks/3d/SKILL.md',
  '07_research_system/paths.mjs',
  '07_research_system/blocks/3d/index.mjs',
  '07_research_system/blocks/3d/create/SKILL.md',
  '07_research_system/blocks/3d/modify/SKILL.md',
  '07_research_system/blocks/3d/inspect/SKILL.md',
  '07_research_system/blocks/3d/export/SKILL.md',
  '07_research_system/blocks/3d/experience-candidates/candidate-template.yaml',
  '07_research_system/blocks/3d/regression/check.mjs',
  '07_research_system/blocks/3d/regression/registry.yaml',
  '07_research_system/blocks/3d/references/external-automation-guide.md',
  '07_research_system/blocks/3d/references/cad-studio-test.md',
  '07_research_system/blocks/3d/references/smoke-test.md',
  '07_research_system/blocks/3d/attribution/solidworks-automation-skill.md',
  '07_research_system/blocks/3d/attribution/EXTERNAL-LICENSE.txt',
  '07_research_system/blocks/3d/scripts/sw_connect.py',
  '07_research_system/blocks/3d/scripts/sw_session.py',
  '07_research_system/blocks/3d/scripts/sw_preflight.py',
  '07_research_system/blocks/3d/scripts/sw_part.py',
  '07_research_system/blocks/3d/scripts/sw_document_data.py',
  '07_research_system/blocks/3d/scripts/sw_entity_reference.py',
  '07_research_system/blocks/3d/scripts/cad_doctor.py',
  '07_research_system/blocks/3d/scripts/sw_review.py',
  '07_research_system/blocks/3d/scripts/sw_export.py',
  '07_research_system/blocks/3d/scripts/cad_installation.py',
  '07_research_system/blocks/3d/tests/index.test.mjs',
  '06_external_lib/README.md',
  '06_external_lib/library-registry.json',
  '06_external_lib/library-manifest.json',
  '.codex/skills/muion-project/scripts/external-lib-sync.mjs',
  '.codex/skills/muion-project/scripts/record-experience.mjs',
  '.codex/skills/muion-project/scripts/summarize-experiences.mjs',
  '00_project/traceability/experiences/README.md',
  '07_research_system/blocks/geant4/SKILL.md',
  '07_research_system/blocks/geant4/index.mjs',
  '07_research_system/blocks/geant4/scripts/preflight.mjs',
  '07_research_system/blocks/geant4/scripts/build.mjs',
  '07_research_system/blocks/geant4/scripts/smoke.mjs',
  '07_research_system/blocks/geant4/scripts/run.mjs',
  '07_research_system/blocks/geant4/scripts/validate.mjs',
  '07_research_system/blocks/geant4/scripts/summarize.mjs',
  '07_research_system/blocks/geant4/experience-candidates/candidate-template.yaml',
  '07_research_system/blocks/geant4/tests/fixtures/mvp-smoke/CMakeLists.txt',
  '07_research_system/blocks/geant4/tests/fixtures/mvp-smoke/main.cc',
  '07_research_system/blocks/geant4/tests/smoke.mjs',
  '00_project/traceability/capability-map.yaml',
  '00_project/traceability/variable-catalog.yaml',
  '00_project/schemas/milestone-manifest.schema.json',
  '00_project/schemas/workflow-run.schema.json',
  '.codex/skills/muion-project/scripts/task-close.mjs',
  '.codex/skills/muion-project/scripts/delivery-plan.mjs',
  '.codex/skills/muion-project/scripts/record-sync-metadata.mjs',
  '00_project/traceability/VARIABLE_CATALOG.md',
  '00_project/traceability/VARIABLE_CATALOG.csv',
  '00_project/templates/task-card.yaml',
  '00_project/task-cards/TASK-SYNC-TOOLCHAIN-EXPERIENCE-001.task-manifest.json',
  '00_project/task-cards/TASK-RESEARCH-ORCHESTRATOR-001.task-manifest.json',
  '07_research_system/control/contracts/README.md',
  '07_research_system/control/contracts/geometry-task.yaml',
  '07_research_system/control/contracts/comsol-task.yaml',
  '07_research_system/control/contracts/g4-task.yaml',
  '07_research_system/control/contracts/result-issue-report.yaml',
  '07_research_system/control/contracts/index.mjs',
  '07_research_system/control/research-state/index.mjs',
  '07_research_system/control/research-state/track.mjs',
  '07_research_system/control/research-state/state.yaml',
  '07_research_system/control/research-state/NOW.md',
  '07_research_system/control/research-state/open-problems.yaml',
  '07_research_system/control/research-state/decision-log.md',
  '07_research_system/control/research-state/events.jsonl',
  '07_research_system/control/research-workflow/SKILL.md',
  '07_research_system/control/research-workflow/README.md',
  '07_research_system/control/research-workflow/index.mjs',
  '07_research_system/control/research-workflow/scripts/contracts.mjs',
  '07_research_system/control/research-workflow/scripts/adapters.mjs',
  '07_research_system/control/research-workflow/references/goal-management.md',
  '07_research_system/control/research-workflow/references/physics-reasoning.md',
  '07_research_system/control/research-workflow/references/task-routing.md',
  '07_research_system/control/research-workflow/references/sub-agent-dispatch.md',
  '07_research_system/control/research-workflow/references/failure-diagnosis.md',
  '07_research_system/control/research-workflow/references/open-problem-tracking.md',
  '07_research_system/control/research-workflow/references/research-report.md',
  '.codex/skills/research-workflow/SKILL.md',
  '.codex/skills/research-workflow/agents/openai.yaml',
  '00_project/templates/run-manifest.yaml',
  '03_runs/fast-track/README.md',
  '03_runs/formal/README.md',
  '90_migration/from-D-muIon/README.md'
];
for (const retired of ['3d', 'comsol', 'contracts', 'geant4', 'research-state', 'research-workflow']) {
  if (fs.existsSync(path.join(root, retired))) throw new Error(`retired root directory still exists: ${retired}`);
}
const missing = required.filter((file) => !fs.existsSync(path.join(root, file)));
if (missing.length) throw new Error(`missing required files: ${missing.join(', ')}`);
const catalog = parseYamlFile(path.join(root, '00_project/traceability/variable-catalog.yaml'));
if (!Array.isArray(catalog.variables) || catalog.variables.length < 1) throw new Error('variable catalog has no variables');
const validation = spawnSync(process.execPath, ['.codex/skills/muion-project/scripts/validate-variable-catalog.mjs'], { cwd: root, encoding: 'utf8' });
if (validation.status !== 0) throw new Error(`variable catalog validation failed: ${validation.stdout}${validation.stderr}`);
const preflight = spawnSync(process.execPath, ['.codex/skills/muion-project/scripts/preflight.mjs', '.'], { cwd: root, encoding: 'utf8' });
if (preflight.status !== 0) throw new Error(`preflight failed: ${preflight.stdout}${preflight.stderr}`);
const migrationNote = fs.readFileSync(path.join(root, '90_migration/from-D-muIon/README.md'), 'utf8');
if (!migrationNote.includes('复制') || !migrationNote.includes('不删除')) throw new Error('legacy migration boundary is missing');
console.log(JSON.stringify({ valid: true, requiredFiles: required.length, variables: catalog.variables.length, legacyWorkspaceUntouched: true }, null, 2));
