import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path'; import crypto from 'node:crypto'; import {createRequire} from 'node:module'; import {handler} from '../11_tools/research-dashboard/server.mjs';
import {validateEvidenceNote} from '../11_tools/research-dashboard/evidence-notes.mjs';
import {inspectPhysicsContract} from '../11_tools/research-dashboard/physics-gate.mjs';
import {reviewClosure} from '../11_tools/research-dashboard/review-closure.mjs';
import {compareCapability} from '../11_tools/research-dashboard/capability-matrix.mjs';
import {normalizeLedger} from '../11_tools/research-dashboard/ledger-normalizer.mjs';
import {isDashboardSession, readCodexSessions, withDisplayNames} from '../11_tools/project-supervisor/progress-aggregator.mjs';
function request(method,url){return new Promise((resolve,reject)=>{const req={method,url};const chunks=[];const res={writeHead:(s,h)=>{res.statusCode=s;res.headers=h},end:b=>resolve({status:res.statusCode,body:String(b||''),headers:res.headers})};try{handler(req,res)}catch(e){reject(e)}})}
test('dashboard routes are read-only',async()=>{assert.equal((await request('GET','/')).status,200);const api=await request('GET','/api/status');assert.equal(api.status,200);const data=JSON.parse(api.body);assert.ok(data.display);assert.ok(Array.isArray(data.warnings));for(const m of ['POST','PUT','DELETE']) assert.equal((await request(m,'/api/status')).status,405);assert.equal((await request('GET','/bad')).status,404)});
test('dashboard exposes the farmer emergency pause instead of stale healthy process state',async()=>{const data=JSON.parse((await request('GET','/api/status')).body);const control=fs.existsSync(path.join(process.cwd(),'_work/current/farmer/control.json'))?JSON.parse(fs.readFileSync(path.join(process.cwd(),'_work/current/farmer/control.json'),'utf8')):null;if(control?.disabled) assert.equal(data.system_services?.services?.farmer?.status,'disabled');});
test('dashboard status uses its live process identity instead of stale supervisor PID',async()=>{const data=JSON.parse((await request('GET','/api/status')).body);assert.equal(data.system_services?.services?.dashboard?.pid,process.pid);assert.equal(data.system_services?.services?.dashboard?.status,'healthy');});
test('no workflow gives null progress when applicable',async()=>{const d=JSON.parse((await request('GET','/api/status')).body);if(!d.workflow) assert.equal(d.display.progress.value,null)});
test('goal checkpoint adapter is read-only and optional',async()=>{const d=JSON.parse((await request('GET','/api/status')).body);assert.ok(d.display.checkpoint);assert.ok(Array.isArray(d.display.checkpoint.goals));});
test('continuation summary is read-only and evidence based',async()=>{const d=JSON.parse((await request('GET','/api/status')).body);assert.ok(d.display.continuation);assert.ok(Array.isArray(d.display.continuation.source));assert.ok('next_action' in d.display.continuation);});
test('convergence guard remains advisory and does not complete state',async()=>{const d=JSON.parse((await request('GET','/api/status')).body);assert.ok(['continue','stop'].includes(d.display.convergence.decision));assert.equal(typeof d.display.convergence.complete,'boolean');});
test('repeated polling leaves canonical state unchanged',async()=>{const files=['07_research_system/control/research-state/state.yaml','07_research_system/control/research-state/events.jsonl','07_research_system/control/research-state/open-problems.yaml'];const before=files.map(f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'));await request('GET','/api/status');await request('GET','/api/status');const after=files.map(f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'));assert.deepEqual(after,before);});
test('evidence notes enforce conclusion levels without becoming state',()=>{assert.equal(validateEvidenceNote({facts:[],evidence:[],conclusion:[],conclusion_level:'confirmed',risks:[],next_steps:[]}).valid,true);assert.equal(validateEvidenceNote({facts:[],evidence:[],conclusion:[],conclusion_level:'made-up',risks:[],next_steps:[]}).valid,false);});
test('health summary is advisory and records stale activity',async()=>{const d=JSON.parse((await request('GET','/api/status')).body);assert.ok(Array.isArray(d.display.health));});
test('physics gate is advisory and contract-preserving',()=>{const r=inspectPhysicsContract({objective:'x',initial_conditions:{},boundary_conditions:{},validation_requirements:['v']});assert.equal(r.status,'ready-for-module-validation');assert.equal(r.preserves_contract,true);});
test('review closure requires evidence and rerun validation',()=>{assert.equal(reviewClosure({status:'closed',severity:'P1',evidence:['x'],fix:'y',rerun_validation:true}).closed,true);assert.equal(reviewClosure({status:'closed',severity:'P1'}).closed,false);});
test('capability comparison is manual and evidence gated',()=>{const r=compareCapability({capability_id:'team'},{capability_id:'team',revision:'r',license:'MIT',hash:'h',tests:'t'});assert.equal(r.recommended,'reference-only');assert.equal(r.manual_adoption_required,true);assert.equal(r.install_executed,false);});
test('ledger normalization preserves runtime trace fields',()=>{const r=normalizeLedger({run_id:'r',session_id:'s',selected_model:'m',reasoning:'xhigh',provider:'p',status:'running',unresolved_items:['u']});assert.equal(r.run,'r');assert.equal(r.model,'m');assert.equal(r.backend,'p');assert.deepEqual(r.unresolved_items,['u']);});
test('research workflow validation exposes advisory physics gate',async()=>{const mod=await import('../07_research_system/control/research-workflow/index.mjs');const r=mod.validateResearchContract({objective:'x',initial_conditions:{},boundary_conditions:{},validation_requirements:['v']});assert.ok(r.advisory_physics_gate);assert.equal(r.advisory_physics_gate.preserves_contract,true);});
test('session read model uses readable unique names without exposing hash ids',()=>{
 const rows=withDisplayNames([{session_id:'a',task_id:'task_validation_001'},{session_id:'b',task_id:'session-1789285330916-29748-81f0a2',branch:'codex/session/session-1789285330916-29748-81f0a2'},{session_id:'c',display_name:'主研究'},{session_id:'d',display_name:'主研究'}]);
 assert.equal(rows[0].display_name,'validation'); assert.equal(rows[1].display_name,null); assert.equal(rows[1].display_name_source,'missing'); assert.equal(rows[2].display_name,'主研究 · 1'); assert.equal(rows[3].display_name,'主研究 · 2'); assert.ok(rows[2].display_name_conflict);
 assert.doesNotMatch(rows.map(row=>row.display_name).join('\n'),/1789285330916|81f0a2/);
});
test('dashboard omits expired sessions but keeps interrupted work visible',()=>{
 const now=Date.parse('2026-09-23T00:00:00Z');
 assert.equal(isDashboardSession({status:'active',lease_until:'2026-09-22T00:00:00Z'},now),false);
 assert.equal(isDashboardSession({status:'expired',lease_until:'2026-09-22T00:00:00Z'},now),false);
 assert.equal(isDashboardSession({status:'abandoned',lease_until:'2026-09-22T00:00:00Z'},now),true);
 assert.equal(isDashboardSession({status:'blocked',lease_until:'2026-09-22T00:00:00Z'},now),true);
});
test('Codex index keeps named incomplete threads and filters completed or unnamed threads',()=>{
 const home=fs.mkdtempSync(path.join(os.tmpdir(),'muion-codex-index-')); const statePath=path.join(home,'state_5.sqlite'); const historyPath=path.join(home,'thread_history_1.sqlite');
 try {
  const {DatabaseSync}=createRequire(import.meta.url)('node:sqlite'); const state=new DatabaseSync(statePath); const history=new DatabaseSync(historyPath);
  state.exec('CREATE TABLE threads (id TEXT, name TEXT, title TEXT, cwd TEXT, archived INTEGER, updated_at INTEGER, updated_at_ms INTEGER, source TEXT, rollout_path TEXT)');
  history.exec('CREATE TABLE thread_turns (thread_id TEXT, status TEXT, started_at INTEGER, completed_at INTEGER, rollout_ordinal INTEGER)');
  const addThread=state.prepare('INSERT INTO threads VALUES (?,?,?,?,?,?,?,?,?)'); const addTurn=history.prepare('INSERT INTO thread_turns VALUES (?,?,?,?,?)'); const root=process.cwd();
  const activePath=path.join(home,'active.jsonl'); const donePath=path.join(home,'done.jsonl'); const unnamedPath=path.join(home,'unnamed.jsonl'); for(const file of [activePath,donePath,unnamedPath]) fs.writeFileSync(file,'');
  addThread.run('active-thread','进行中任务','',root,0,0,Date.now(),'vscode',activePath); addTurn.run('active-thread','inProgress',Math.floor(Date.now()/1000),null,1);
  addThread.run('done-thread','已完成任务','',root,0,0,Date.now(),'vscode',donePath); addTurn.run('done-thread','completed',Math.floor(Date.now()/1000)-10,Math.floor(Date.now()/1000),1);
  addThread.run('unnamed-thread',null,'',root,0,0,Date.now(),'vscode',unnamedPath); addTurn.run('unnamed-thread','interrupted',Math.floor(Date.now()/1000)-10,null,1);
  state.close(); history.close();
  const warnings=[]; const result=readCodexSessions(root,warnings,{codexHome:home});
  assert.deepEqual(result.sessions.map(session=>session.display_name),['进行中任务']); assert.ok(result.terminal_ids.has('done-thread')); assert.deepEqual(warnings,[]);
 } finally { fs.rmSync(home,{recursive:true,force:true}); }
});
test('existing session uses a readable task or Codex thread name',async()=>{const data=JSON.parse((await request('GET','/api/status')).body);const row=data.supervision.sessions.find(session=>session.task_id==='task_project_supervisor_auto_recovery_001');if(row){assert.ok(row.display_name);assert.doesNotMatch(row.display_name,/^[a-f0-9-]{20,}$/i);assert.ok(['task_name','display_name','codex-thread-name'].includes(row.display_name_source));}});
test('dashboard board excludes terminal sessions from the work list',async()=>{const data=JSON.parse((await request('GET','/api/status')).body);assert.ok(data.supervision.sessions.every(session=>!['closed','complete','completed','done','succeeded','success'].includes(String(session.status||'').toLowerCase())));});
test('dashboard page has a semantic session surface and keeps raw state secondary',async()=>{const page=(await request('GET','/')).body;assert.match(page,/id="session-list"/);assert.match(page,/<details class="panel raw">/);assert.doesNotMatch(page,/JSON\.stringify\(d\.display/);});
test('dashboard reads JSON-backed yaml state as structured data',async()=>{const data=JSON.parse((await request('GET','/api/status')).body);assert.equal(typeof data.research_state.state_revision,'number');assert.equal(typeof data.research_state.current_task?.task_id,'string');assert.equal(data.display.current.task.task_id,data.research_state.current_task.task_id);assert.ok(Array.isArray(data.display.open_problems));});
test('dashboard separates current session freshness from historical research-state time',async()=>{const data=JSON.parse((await request('GET','/api/status')).body);assert.ok(data.generated_at);assert.ok(data.supervision.generated_at);assert.ok(data.supervision.observed_at);assert.ok(data.supervision.current_session);assert.ok(data.supervision.current_session.dashboard_observed_at);assert.ok(data.display.consistency);assert.ok(['matched','mismatch','unregistered','stale','unknown'].includes(data.display.consistency.status));assert.equal(typeof data.supervision.counts.stale,'number');assert.ok(['session-registry','runtime-session','codex-thread'].includes(data.supervision.current_session.source));for(const session of data.supervision.sessions) assert.equal(typeof session.stale,'boolean');});
test('live Codex work uses its readable thread name and keeps incomplete turns visible',async()=>{const data=JSON.parse((await request('GET','/api/status')).body);const current=data.supervision.current_session;if(current.source==='codex-thread'){assert.ok(current.display_name);assert.equal(current.status,'active');assert.equal(current.mode,'codex');assert.doesNotMatch(current.display_name,/01a[0-9a-f-]{20,}/i);assert.equal(data.display.consistency.status,'unregistered');}});
test('dashboard page exposes current-session freshness, consistency and todo surfaces',async()=>{const page=(await request('GET','/')).body;for(const id of ['current-session-title','current-session-meta','current-session-badge','current-session-observed','dashboard-observed','research-state-updated','metric-stale','consistency-badge','consistency-note','todo-list']) assert.match(page,new RegExp(`id="${id}"`));});
test('dashboard refresh policy stays below the ten-second freshness threshold',()=>{const script=fs.readFileSync(path.join(process.cwd(),'11_tools/research-dashboard/supervision.js'),'utf8');assert.match(script,/setInterval\(refresh, 3000\)/);assert.match(script,/lastResponseAt/);});
